name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "v0.0.0")
          echo "Latest Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          TAG=${{ env.tag }}
          if [ "$TAG" = "v0.0.0" ]; then
            NEW_TAG="v0.1.0"
          else
            IFS='.' read -r -a VERSION <<< "${TAG#v}"
            NEW_TAG="v${VERSION[0]}.${VERSION[1]}.$((${VERSION[2]}+1))"
          fi
          echo "New Version: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV

      - name: Update Version in build.gradle
        run: |
          NEW_TAG=${{ env.new_tag }}
          sed -i "s/version = '.*'/version = '$NEW_TAG'/" build.gradle

      - name: Commit and Push New Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add build.gradle
          git commit -m "Bump version to ${{ env.new_tag }}"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
          git push origin master

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the token input here
          tag_name: ${{ env.new_tag }}
          release_name: ${{ env.new_tag }} Release
          body: "Description of the release."
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/*.jar
          asset_name: my-application.jar
          asset_content_type: application/java-archive

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate and submit dependency graph
        run: ./gradlew dependencies --configuration runtimeClasspath | tee dependency-graph.txt

      - name: Upload dependency graph
        uses: actions/upload-artifact@v3
        with:
          name: dependency-graph
          path: dependency-graph.txt
